name: Build Static PHP (aarch64 musl)

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 安装 musl 工具链
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y \
            wget xz-utils tar \
            aarch64-linux-musl-gcc

      - name: 下载静态依赖
        run: |
          mkdir -p /tmp/musl-static
          # 下载预编译的静态库 (AltLinux 源)
          wget -nv https://deps.altlinux.org/static/aarch64/openssl-3.3.1-aarch64-musl-static.tar.xz -O /tmp/openssl.tar.xz
          tar -xJf /tmp/openssl.tar.xz -C /tmp/musl-static
          
          wget -nv https://deps.altlinux.org/static/aarch64/curl-8.8.0-aarch64-musl-static.tar.xz -O /tmp/curl.tar.xz
          tar -xJf /tmp/curl.tar.xz -C /tmp/musl-static
          
          wget -nv https://deps.altlinux.org/static/aarch64/sqlite-3.45.2-aarch64-musl-static.tar.xz -O /tmp/sqlite.tar.xz
          tar -xJf /tmp/sqlite.tar.xz -C /tmp/musl-static

      - name: 构建 PHP
        run: |
          wget -nv https://www.php.net/distributions/php-8.3.9.tar.gz
          tar -xzf php-8.3.9.tar.gz
          cd php-8.3.9
          
          export CC="aarch64-linux-musl-gcc"
          export CXX="aarch64-linux-musl-g++"
          export AR="aarch64-linux-musl-ar"
          export RANLIB="aarch64-linux-musl-ranlib"
          export STRIP="aarch64-linux-musl-strip"
          export CFLAGS="-static -Os -I/tmp/musl-static/include"
          export LDFLAGS="-static -L/tmp/musl-static/lib"
          
          ./configure \
            --host=aarch64-linux-musl \
            --prefix=/usr/local/php \
            --disable-shared \
            --enable-static \
            --enable-cli \
            --enable-fpm \
            --with-openssl \
            --with-curl \
            --with-zlib \
            --with-pdo-sqlite \
            --with-sqlite3 \
            --enable-mbstring \
            --enable-json \
            --enable-xml \
            --enable-simplexml \
            --enable-dom \
            --enable-phar \
            --enable-zip \
            --enable-opcache \
            --enable-cgi \
            --without-pear \
            ac_cv_func_dlopen=no \
            ac_cv_func_dlsym=no
          
          make -j$(nproc)
          $STRIP sapi/cli/php
          $STRIP sapi/fpm/php-fpm

      - name: 打包二进制
        run: |
          mkdir -p php-bin
          cp php-8.3.9/sapi/cli/php php-bin/
          cp php-8.3.9/sapi/fpm/php-fpm php-bin/
          tar -czvf php-static-bin.tar.gz php-bin/

      - name: 上传制品
        uses: actions/upload-artifact@v4
        with:
          name: php-static-bin
          path: php-static-bin.tar.gz