name: Build PHP for Android (aarch64 static)

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install basic tools
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y \
            gcc-aarch64-linux-gnu g++-aarch64-linux-gnu \
            libc6-dev-arm64-cross \
            build-essential autoconf automake libtool \
            bison re2c pkg-config

      - name: Download prebuilt static libraries
        run: |
          mkdir -p /tmp/static-libs
          # 下载预编译的静态OpenSSL
          wget -nv https://github.com/openssl/openssl/releases/download/openssl-3.3.1/openssl-3.3.1-static-linux-arm64.tar.gz -O /tmp/openssl.tar.gz
          tar -xzf /tmp/openssl.tar.gz -C /tmp/static-libs
          
          # 下载预编译的静态cURL
          wget -nv https://curl.se/download/curl-8.8.0-static-arm64.tar.gz -O /tmp/curl.tar.gz
          tar -xzf /tmp/curl.tar.gz -C /tmp/static-libs

      - name: Download and build PHP
        run: |
          wget -nv https://www.php.net/distributions/php-8.3.9.tar.gz
          tar -xzf php-8.3.9.tar.gz
          cd php-8.3.9
          
          export CC="aarch64-linux-gnu-gcc"
          export CXX="aarch64-linux-gnu-g++"
          export AR="aarch64-linux-gnu-ar"
          export RANLIB="aarch64-linux-gnu-ranlib"
          export STRIP="aarch64-linux-gnu-strip"
          export CFLAGS="-static -Os"
          export LDFLAGS="-static -Wl,--gc-sections"
          
          ./configure \
            --host=aarch64-linux-gnu \
            --prefix=/data/local/tmp/php \
            --disable-shared \
            --enable-static \
            --enable-cli \
            --with-openssl=/tmp/static-libs \
            --with-curl=/tmp/static-libs \
            --without-pear \
            ac_cv_func_dlopen=no \
            ac_cv_func_dlsym=no
          
          make -j$(nproc)
          aarch64-linux-gnu-strip sapi/cli/php

      - name: Package binary
        run: |
          mkdir -p php-dist
          cp php-8.3.9/sapi/cli/php php-dist/
          tar -czvf php-aarch64-static.tar.gz php-dist/

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: php-aarch64-static
          path: php-aarch64-static.tar.gz