name: Build PHP for Android (aarch64 static)

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up ARM64 environment
        run: |
          sudo dpkg --add-architecture arm64
          sudo apt-get update -qq
          sudo apt-get install -y \
            gcc-aarch64-linux-gnu g++-aarch64-linux-gnu \
            libc6-dev-arm64-cross \
            libssl-dev:arm64 libssl-static:arm64 \
            libcurl4-openssl-dev:arm64 libcurl4-openssl-static:arm64 \
            zlib1g-dev:arm64 zlib1g-static:arm64 \
            libsqlite3-dev:arm64 libsqlite3-static:arm64 \
            build-essential autoconf automake libtool bison re2c pkg-config

      - name: Download PHP source
        run: |
          wget -nv https://www.php.net/distributions/php-8.3.9.tar.gz
          tar -xzf php-8.3.9.tar.gz
          mv php-8.3.9 php-src

      - name: Configure PHP
        run: |
          cd php-src
          export CC="aarch64-linux-gnu-gcc"
          export CXX="aarch64-linux-gnu-g++"
          export AR="aarch64-linux-gnu-ar"
          export RANLIB="aarch64-linux-gnu-ranlib"
          export STRIP="aarch64-linux-gnu-strip"
          export CFLAGS="-static -Os -ffunction-sections -fdata-sections"
          export LDFLAGS="-static -Wl,--gc-sections"
          export PKG_CONFIG_PATH="/usr/lib/aarch64-linux-gnu/pkgconfig"
          
          ./configure \
            --host=aarch64-linux-gnu \
            --prefix=/data/local/tmp/Android-tools/usr/ \
            --disable-shared \
            --enable-static \
            --enable-cli \
            --enable-fpm \
            --with-openssl \
            --with-curl \
            --with-zlib \
            --enable-mbstring \
            --enable-json \
            --enable-xml \
            --enable-simplexml \
            --enable-dom \
            --enable-phar \
            --enable-zip \
            --enable-opcache \
            --enable-cgi \
            --with-sqlite3 \
            --with-pdo-sqlite \
            --without-pear \
            ac_cv_func_dlopen=no \
            ac_cv_func_dlsym=no

      - name: Build PHP
        run: |
          cd php-src
          make -j$(nproc)
          aarch64-linux-gnu-strip sapi/cli/php
          aarch64-linux-gnu-strip sapi/fpm/php-fpm

      - name: Package binaries
        run: |
          mkdir -p php-bin
          cp php-src/sapi/cli/php php-bin/
          cp php-src/sapi/fpm/php-fpm php-bin/
          cp php-src/php.ini-development php-bin/php.ini
          cp php-src/sapi/fpm/php-fpm.conf php-bin/
          tar -czvf php-aarch64-static.tar.gz php-bin/

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: php-aarch64-static
          path: php-aarch64-static.tar.gz