name: Build Static PHP (aarch64 musl)

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 设置工具链
        run: |
          # 安装基础编译工具
          sudo apt-get update -qq
          sudo apt-get install -y build-essential wget xz-utils
          
          # 从官方源下载 musl 工具链
          mkdir -p /opt/musl
          wget --tries=3 --timeout=30 https://more.musl.cc/x86_64-linux-musl/aarch64-linux-musl-cross.tgz -O /tmp/musl.tgz || \
          wget --tries=3 --timeout=30 https://more.musl.cc/x86_64-linux-musl/aarch64-linux-musl-cross.tgz -O /tmp/musl.tgz
          tar -xzf /tmp/musl.tgz -C /opt/musl --strip-components=1
          echo "/opt/musl/bin" >> $GITHUB_PATH

      - name: 下载依赖库
        run: |
          mkdir -p /tmp/static-libs
          
          # 从 Alpine 官方仓库下载静态库
          wget --tries=3 --timeout=30 \
            https://dl-cdn.alpinelinux.org/alpine/v3.18/releases/aarch64/{openssl-static-3.1.4-r0.aarch64.apk,curl-static-8.4.0-r0.aarch64.apk} \
            -P /tmp/
          
          # 提取静态库
          for pkg in /tmp/*.apk; do
            tar -xzf "$pkg" -C /tmp/static-libs --wildcards '*.a' '*.h' --transform 's/usr\///'
          done

      - name: 构建 PHP
        run: |
          wget --tries=3 --timeout=30 https://www.php.net/distributions/php-8.3.9.tar.gz
          tar -xzf php-8.3.9.tar.gz
          cd php-8.3.9
          
          export CC="aarch64-linux-musl-gcc"
          export CXX="aarch64-linux-musl-g++"
          export AR="aarch64-linux-musl-ar"
          export RANLIB="aarch64-linux-musl-ranlib"
          export STRIP="aarch64-linux-musl-strip"
          export CFLAGS="-static -Os -I/tmp/static-libs/include"
          export LDFLAGS="-static -L/tmp/static-libs/lib"
          
          ./configure \
            --host=aarch64-linux-musl \
            --prefix=/data/local/tmp/Android-tools/usr/ \
            --disable-shared \
            --enable-static \
            --enable-cli \
            --enable-fpm \
            --with-openssl \
            --with-curl \
            --without-pear
          
          make -j$(nproc)
          $STRIP sapi/cli/php
          $STRIP sapi/fpm/php-fpm

      - name: 打包成品
        run: |
          mkdir -p php-bin
          cp php-8.3.9/sapi/cli/php php-bin/
          cp php-8.3.9/sapi/fpm/php-fpm php-bin/
          tar -czvf php-static.tar.gz php-bin/

      - name: 上传制品
        uses: actions/upload-artifact@v4
        with:
          name: php-static-bin
          path: php-static.tar.gz