name: Build Static PHP (aarch64 musl)

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 下载 musl 工具链
        run: |
          mkdir -p /opt/musl
          wget -nv https://musl.cc/aarch64-linux-musl-cross.tgz -O /tmp/musl.tgz
          tar -xzf /tmp/musl.tgz -C /opt/musl --strip-components=1
          echo "/opt/musl/bin" >> $GITHUB_PATH

      - name: 下载静态依赖库
        run: |
          mkdir -p /tmp/static-libs
          # 使用 Alpine Linux 的预编译包 (musl 原生兼容)
          wget -nv https://dl-cdn.alpinelinux.org/alpine/v3.18/releases/aarch64/openssl-static-3.1.4-r0.aarch64.apk -O /tmp/openssl.apk
          tar -xzf /tmp/openssl.apk -C /tmp/static-libs --wildcards '*.a' '*.h'
          
          wget -nv https://dl-cdn.alpinelinux.org/alpine/v3.18/releases/aarch64/curl-static-8.4.0-r0.aarch64.apk -O /tmp/curl.apk
          tar -xzf /tmp/curl.apk -C /tmp/static-libs --wildcards '*.a' '*.h'

      - name: 构建 PHP
        run: |
          wget -nv https://www.php.net/distributions/php-8.3.9.tar.gz
          tar -xzf php-8.3.9.tar.gz
          cd php-8.3.9
          
          export CC="aarch64-linux-musl-gcc"
          export CXX="aarch64-linux-musl-g++"
          export AR="aarch64-linux-musl-ar"
          export RANLIB="aarch64-linux-musl-ranlib"
          export STRIP="aarch64-linux-musl-strip"
          export CFLAGS="-static -Os -I/tmp/static-libs/usr/include"
          export LDFLAGS="-static -L/tmp/static-libs/usr/lib"
          
          ./configure \
            --host=aarch64-linux-musl \
            --prefix=/data/local/tmp/Android-tools/usr/ \
            --disable-shared \
            --enable-static \
            --enable-cli \
            --enable-fpm \
            --with-openssl \
            --with-curl \
            --without-pear
          
          make -j$(nproc)
          $STRIP sapi/cli/php
          $STRIP sapi/fpm/php-fpm

      - name: 打包成品
        run: |
          mkdir -p php-bin
          cp php-8.3.9/sapi/cli/php php-bin/
          cp php-8.3.9/sapi/fpm/php-fpm php-bin/
          tar -czvf php-static.tar.gz php-bin/

      - name: 上传制品
        uses: actions/upload-artifact@v4
        with:
          name: php-static-bin
          path: php-static.tar.gz