name: Build PHP for Android

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [aarch64-linux]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

       - name: Install missing aarch64 libc & patch script
      run: |
        sudo apt-get install -y libc6-dev-arm64-cross gcc-aarch64-linux-gnu g++-aarch64-linux-gnu
        cd PHP-for-Android-compiler
        sed -i 's|./configure -O3|CFLAGS="-O3" ./configure|g' compileandroid.sh
        chmod +x compileandroid.sh


      - name: Clone compiler
        run: |
          git clone --depth=1 https://github.com/BXXD101/PHP-for-Android-compiler.git

      - name: Cross-compile PHP
        run: |
          cd PHP-for-Android-compiler
          chmod +rwx *
          ./compileandroid.sh ${{ matrix.arch }}

      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: php-${{ matrix.arch }}
          path: PHP-for-Android-compiler/php
